language: node_js
node_js:
  - 6.1

deploy:
  provider: npm
  email: npm@travi.org
  api_key:
    secure: OotwQLSetZwegEdyBsSgaCEJqXmFS9/7udfMMdXgFBU/MrWnX52ZKCDMvU+5VpNHG+m7tWQ8pCkF3uCmNa29JBHQYE5IZW04jjABTMlHjvxBigB81sMat8n5S+9moXc/cfE/5iEdk1VSqc0XTiPdL7cUvRcM9tjmkqa3hCfNsjlf1gPyhuCWvIkaYvfHw4Y3d+q6xS9wN+RgB/s6EmcrpnRdITVIfkcA3EuchNWVOWUykIBppoiXgg3ll3S2zY/15ooYZtAozG06wz3pnUWnYp2x1aZ2k5P4vDHfoXh0ZyNowS0LJfCNOz7hC/2eXRuLtvNWIxapfIp4aUce92mHEB5mSXj2ZrvCvWoCMkusDpzfNWZvb6TPgsr7R8qNt4MtlJ416ym1ykLHl0FyTWUZIUFWhD+lMwMrfYlqU0NLw02pSn+jA5GfQwRLf6Pd7D3Vf1Sxt+W6xypeoRq+RREj2a3LR4HqdFZRlMbEkLeaT9FZpa0UYy1j2LdseSsVJXYbU4RJa18czV/2buyUpZNIKlKlavQ1kYYDjhAUZBe1La+2C+MgBzeUQk41U5V8RbV+QBOuvd5A0kWbu36UHzqi6p5Wb7aUVlPqWcsenLyyOSJfNaEuodoj0BhtoD/IkEIZF7FzxviVgEyyi4nz36RRazgznr834Cn3KX86VJSM/ec=
  on:
    tags: true
    repo: travi/any
