language: node_js
after_success:
  - npm run report-coverage
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: LY9EdvZBFG4r/rZ7tLqsJBEGqJ+BbC5PgwIZaZ1P+g4sXiKCje9Af61k9/3CU7zWYF4KNevOidsZjgYO6kI049CqtceZgv3DB3cQ3+yEa+H7BU3wyip/cgvGc+Qdef53auKhM1O9jtryMOAJ8VgIbfsWqaMiumKNk9eBWVQpWM46d2KmFoqX0ro0iglenaLF92GyRUeOsjgTwi+4wYTf41/ACIHfIKvGY2L4r0PiX2zMUDsBCb4r2BxGyw2t3dQRQfK9sDAZ3ShLkun3KytCVlBI0JtfeF+/GC8CeYwdoa0uua5JpZB5MtsvPn4X8zI3YgZL1H2WWE9sqcnOZALmDpzq+EYTU2l4mXYaO/qwdVfoCgn/VGflkZRESBuTPT6bwvW73imdhwahh+U4n/9LUZgcr1GLsELfg6uAlwlzD697tFivxEv10iX3TBqS2GZj/mxJaVLb2X2Ob2kNPTFCXG/LlY+ZjtWzfQsJ2RygP3xnU598uidPirqQtCLOVGfoUrc0mWl7Vyws5BlHhg64frs541s1criUjwq9+7Rp/qXMm49aGuLsWBUrIoE87JN6ELcdDSjOPDKdCv9jLpPysVAi1G1vn29Y8ghvai8LKP/dyc8EB0oblDYW5pkGG6p218kZhMOnfpu86xhXgZoM7Ya4tqDioCrj9LU5yJZa7jQ=
