language: node_js
node_js:
- 6.1
deploy:
  provider: npm
  email: npm@travi.org
  on:
    tags: true
    repo: travi/any
  api_key:
    secure: QHN5dQS5RjGMJo4RS8mDSViQg8+xeZeNYGODglf0BhU5rmZjFbs9PYjfGwt03XMvZ6gHcxiSebMtYxvTwPJpr8HCS2Cxt3MwczEFMeVTAwOYBaFq/A8PFe/CDu/l2tg63hH53Mko4jZwbaRJjOtnpuujfl/NkQuxdifEclV6igpaBLUQNsfxt3T1UZ031CHHKvCgAVCPuAgm1mjsU+M7XNDWb1n5KXIeF4Hf8AZk1lPmTbUTi+9eTNKj4WtWXx9rG0otEuhSDN5LXpgYXPQWpdHIjeBMs77qrtslEu6Nopz6Q+flaDzCAaK+BFeccA/WbKuLSoX9c4rZ5gyHN5UTetVZHjrV/Qp56xumNVnOOajKHf67ioguax+wFXChO5ooBYHxz+S35ZKtzzdyIbNGFkiXXt5FItYEoCbbfHs246kuzOiIgkWhN3Q8AsPmM0lIIGJ9CMyfta11Ri+zSlrEUK3bYhXDFSUtlnDNQmtNECO5c+YCCOqvFM3u4R2IfGmmnFeMCZtWr596KHDdfRZPNENeN5+dYokkzLEubbLoUk91XWpCxbaSJElp6fDLLb9OxL257X0/ejDJpXNQUeCfIS4SV2VZ9cdYkxzPc+Z87OtfoTL47sSSfECJ8v9ac5x6v62i31jVBys37SFhpHxHT1u8x67nZCw+KKk/oejKY/0=
