language: node_js
notifications:
  email: false
before_script:
- npm run greenkeeper:update-lockfile
- npm ls --production >/dev/null
script:
- npm test
- npm run semantic-release
after_script: npm run greenkeeper:upload-lockfile
after_success:
  - npm run report-coverage
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - GK_LOCK_COMMIT_AMEND=true
